name = "crypto-indicator-bot"
main = "src/index.js"
compatibility_date = "2023-12-01"

# Workers Cron Triggers 配置
[triggers]
crons = [
  "0 * * * *"      # 每小时执行一次
]

# KV 命名空间绑定
[[kv_namespaces]]
binding = "BOT_STATE"
id = "75ee02ab718b422083ed79e228f80238"
# id = "${KV_NAMESPACE_ID}"

[vars]
# 环境变量将在Cloudflare Workers控制台中设置
# BOT_TOKEN = ""
# USER_ID = ""
# COINMARKETCAP_API_KEY = ""
# KV_NAMESPACE_ID = ""